---
title: "Lab 04 - La Quinta is Spanish for next to Denny's, Pt. 1"
author: "Bob Dwyer"
date: "Insert date here"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(here)
```

```{r load-data, message = FALSE}
#could not install dsbox
#could not load data from url
#manually load data files

load(here("data", "dennys.rda"))
load(here("data", "laquinta.rda"))
states <- read_csv("data/states.csv")
```

### Exercise 1

```{r exercise1}
#What are the dimensions of the Denny’s dataset?
nrow(dennys) 
ncol(dennys) 

#What does each row in the dataset represent?
head(dennys) #each row represents a location


#What are the variables?
glimpse(dennys) #address, city, state, zip, long., lat.
```

### Exercise 2

```{r exercise2}
#What are the dimensions of the LaQuinta’s dataset?
nrow(laquinta) 
ncol(laquinta) 

#What does each row in the dataset represent?
head(laquinta) #each row represents a location


#What are the variables?
glimpse(laquinta) #address, city, state, zip, long., lat.
```

### Exercise 3
```{r exercise3}
#Q: Are there any La Quinta’s locations outside of the US? If so, which countries? What about Denny’s?

#A: There are no Denny's outside of the US, but La Quinta is international. Which was a surprise to me!!
```

### Exercise 4
```{r exercise4}
#Q: Now take a look at the data. What would be some ways of determining whether or not either establishment has any locations outside the US using just the data (and not the websites).

#A: One way would be to use the state or zip code variables. State seems easier.
```

### Exercise 5
```{r exercise5}
#Are there any international Dennys?
#Filter out US locations

intl_dennys <- dennys %>%
  filter(!(state %in% states$abbreviation))

#There are not.
```
### Exercise 6
```{r exercise6}
#Add a country variable to the Denny’s dataset and set all observations equal to "United States."
dennys <- dennys %>%
  mutate(country = "United States")
```
 
### Exercise 7
```{r exercise7}
#Are there any international La Quintas?
#Filter out US locations

intl_laquinta <- laquinta %>%
  filter(!(state %in% states$abbreviation))

#There are 14.
```
### Exercise 8
```{r exercise8}
#Add a country variable to the La Quinta dataset. Use the case_when function to populate this variable. 

laquinta <- laquinta %>%
  mutate(country = case_when(
    state %in% state.abb ~ "United States",
    state %in% c("ON", "BC") ~ "Canada",
    state %in% c("QR", "CH", "NL", "VE", "PU", "SL", "AG") ~ "Mexico",
    state == "ANT" ~ "Colombia",
    state == "FM" ~ "Honduras")
  )

#Going forward we will work with the data from the United States only.
laquinta <- laquinta %>%
  filter(country == "United States")
```
### Exercise 9
```{r exercise9}
#Q: Which states have the most and fewest Denny’s locations? 
dennys %>%
  count(state) %>%
  inner_join(states, by = c("state" = "abbreviation")) %>%
  arrange(area)

#A: California has the most, DE has the fewest.

#Q: What about La Quinta? 
laquinta %>%
  count(state) %>%
  inner_join(states, by = c("state" = "abbreviation")) %>%
  arrange(area)

#A: Texas has the most, ME has the least.

#Q: Is this surprising? Why or why not? 
#A: Not really surprising as larger areas tend to have more of both.
```
### Exercise 10
```{r exercise10}
#Which states have the most Denny’s locations per thousand square miles? What about La Quinta?

#add an identifier variable before combining data sets
dennys <- dennys %>%
  mutate(establishment = "Denny's")
laquinta <- laquinta %>%
  mutate(establishment = "La Quinta")

#combine using bind_rows since the datasets have the same # of columns
dn_lq <- bind_rows(dennys, laquinta)

#We can plot the locations of the two establishments using a scatter plot, and color the points by the establishment type. 

dn_lq %>%
  ggplot(mapping = aes(x = longitude,
                       y = latitude,
                       color = establishment)) +
  geom_point(alpha = .5) +
  theme_bw()+
  labs(title = "Locations of Laquinta and Dennys in US",
       x = "Longitude",
       y = "Latitude",
       color = "Establishment")
```
### Exercise 11
```{r exercise11}
#Filter the data for observations in North Carolina only
dn_lq %>%
  filter(state == "NC") %>%
  ggplot(mapping = aes(x = longitude,
                       y = latitude,
                       color = establishment)) +
  geom_point(alpha = .5) +
  theme_bw()+
  labs(title = "Locations of Laquinta and Dennys in North Carolina",
       x = "Longitude",
       y = "Latitude",
       color = "Establishment")

#Q: Visually, does Mitch Hedberg’s joke appear to hold here?
#A: No.
```
### Exercise 12
```{r exercise12}
#Filter the data for observations in Texas only
dn_lq %>%
  filter(state == "TX") %>%
  ggplot(mapping = aes(x = longitude,
                       y = latitude,
                       color = establishment)) +
  geom_point(size = 3, alpha = .25) +
  theme_bw()+
  labs(title = "Locations of Laquinta and Dennys in Texas",
       x = "Longitude",
       y = "Latitude",
       color = "Establishment")

#Q: Visually, does Mitch Hedberg’s joke appear to hold here?
#A: Haha!
```